# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:
    alfresco:
        build:
          context: ./alfresco
          args:
            ALFRESCO_TAG: ${ALFRESCO_CE_TAG}
            DB: mariadb
            SOLR_COMMS: secret
        mem_limit: 3392m
        depends_on:
            - mysql
        environment:
            JAVA_TOOL_OPTIONS: "
                -Dencryption.keystore.type=JCEKS
                -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
                -Dencryption.keyAlgorithm=DESede
                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
                -Dmetadata-keystore.password=mp6yc0UD9e
                -Dmetadata-keystore.aliases=metadata
                -Dmetadata-keystore.metadata.password=oKIWzVdEdA
                -Dmetadata-keystore.metadata.algorithm=DESede
                "
            JAVA_OPTS : '
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.driver=org.mariadb.jdbc.Driver
                -Ddb.url=jdbc:mariadb://mysql:3306/alfresco?autoReconnect=true\&useUnicode=true\&characterEncoding=UTF-8\&useSSL=false\&allowPublicKeyRetrieval=true
                -Dalfresco_user_store.adminpassword=209c6174da490caeb422f3fa5a7ae634
                -Dsystem.preferred.password.encoding=bcrypt10
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.port.ssl=8983
                -Dsolr.secureComms=secret
                -Dsolr.baseUrl=/solr
                -Dindex.subsystem.name=solr6
                -Dsolr.sharedSecret=r5uz3k7s08p  
                -Dalfresco.host=${SERVER_NAME}
                -Dalfresco.port=80
                -Dapi-explorer.url=http://${SERVER_NAME}:80/api-explorer
                -Dalfresco.protocol=http 
                -Dshare.host=${SERVER_NAME}
                -Dshare.port=80
                -Dshare.protocol=http 
                -Daos.baseUrlOverwrite=http://${SERVER_NAME}/alfresco/aos
                -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dcsrf.filter.enabled=false 
                -Dopencmis.server.override=true
                -Dopencmis.server.value=http://${SERVER_NAME}:80
                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/ 
                -DlocalTransform.ocr.url=http://transform-ocr:8090/ 
                -Dcsrf.filter.enabled=false
                -Dalfresco.restApi.basicAuthScheme=true
                -Dauthentication.protection.enabled=false
                -XX:+UseG1GC -XX:+UseStringDeduplication
                -Dgoogledocs.enabled=true
                -Dmail.host=
                -Dmail.port=
                -Dmail.username=
                -Dmail.password=${SMTP_PASS}
                -Dmail.encoding=UTF-8
                -Dmail.smpt.auth=true
                -Dmail.from.default=
                -Dmail.from.enabled=true
                -Dmail.protocol=smtps
                -Dmail.testmessage.send=true
                -Dmail.testmessage.to=marcos@ambientelivre.com.br
                -Dmail.testmessage.subject=Outbound_SMTP_MARCOS
                -Dmail.testmessage.text=The_Outbound_SMTP_email_subsystem_is_working
                -Xms2880m -Xmx2880m
                -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
            '
        volumes:
            - ./data/alf-repo-data:/usr/local/tomcat/alf_data
            - ./logs/alfresco:/usr/local/tomcat/logs
            - /opt/alfresco/lib/mysql-connector-java-8.0.29-tidb-1.0.2.jar:/usr/local/tomcat/lib/mysql-connector-java-8.0.29-tidb-1.0.2.jar

    transform-core-aio:
        image: alfresco/alfresco-transform-core-aio:${TRANSFORM_ENGINE_TAG}
        mem_limit: 2048m
        environment:
            JAVA_OPTS: "
              -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
              -Dserver.tomcat.threads.max=12
              -Dserver.tomcat.threads.min=4
              -Dlogging.level.org.alfresco.transform.common.TransformerDebug=ERROR
            "

    share:
        build:
          context: ./share
          args:
            SHARE_TAG: ${SHARE_TAG}
            SERVER_NAME: ${SERVER_NAME}
        mem_limit: 848m
        environment:
            REPO_HOST: "alfresco"
            REPO_PORT: "8080"
            CSRF_FILTER_REFERER: "http://localhost:80/.*"
            CSRF_FILTER_ORIGIN: "http://localhost:80"
            JAVA_OPTS: "
                -Xms720m -Xmx720m
                -Dalfresco.context=alfresco
                -Dalfresco.protocol=http
                -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
                "
        volumes:
            - ./logs/share:/usr/local/tomcat/logs

    solr6:
        build:
          context: ./search
          args:
            SEARCH_TAG: ${SEARCH_CE_TAG}
            SOLR_HOSTNAME: solr6
            ALFRESCO_HOSTNAME: alfresco
            ALFRESCO_COMMS: secret 
            CROSS_LOCALE: "true"
            DISABLE_CONTENT_INDEXING: "false"
        mem_limit: 1696m
        environment:
            #Solr needs to know how to register itself with Alfresco
            SOLR_ALFRESCO_HOST: "alfresco"
            SOLR_ALFRESCO_PORT:  "8080" 
            #Alfresco needs to know how to call solr
            SOLR_SOLR_HOST: "solr6"
            SOLR_SOLR_PORT: "8983"
            #Create the default alfresco and archive cores
            SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
            SOLR_JAVA_MEM: "-Xms1440m -Xmx1440m" 
            SOLR_OPTS: "
                -XX:NewSize=592m
                -XX:MaxNewSize=592m
                -Dalfresco.secureComms.secret=r5uz3k7s08p
            "
        volumes:
            - ./data/solr-data:/opt/alfresco-search-services/data
            - ./backup/solr/alfresco:/opt/alfresco-search-services/backup/alfresco
            - ./backup/solr/archive:/opt/alfresco-search-services/backup/archive

    activemq:
        image: alfresco/alfresco-activemq:${ACTIVEMQ_TAG}
        mem_limit: 1g
        ports:
            - 8161:8161
        volumes:
            - ./data/activemq-data:/opt/activemq/data

    content-app:
        image: alfresco/alfresco-content-app:${ACA_TAG}
        mem_limit: 256m
        environment:
            APP_BASE_SHARE_URL: "http://${SERVER_NAME}:80/#/preview/s"
        depends_on:
            - alfresco

    # HTTP proxy to provide HTTP Default port access to services
    # SOLR API and SOLR Web Console are protected to avoid unauthenticated access
    proxy:
        image: nginx:stable-alpine
        mem_limit: 128m
        depends_on:
            - alfresco
            - solr6
            - share
            - content-app
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd
        ports:
            - 80:80

    transform-ocr:
        image: angelborroy/alfresco-tengine-ocr:1.0.0
        mem_limit: 1536m
        environment:
          JAVA_OPTS: "
              -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
              -Dserver.tomcat.threads.max=4
              -Dserver.tomcat.threads.min=1
            "
    camunda-mysql:
        image: camunda/camunda-bpm-platform:latest
        mem_limit: 1989m
        environment:
            - DB_DRIVER=com.mysql.cj.jdbc.Driver
            - DB_URL=jdbc:mysql://mysql:3306/camunda?sendFractionalSeconds=false
            - DB_USERNAME=camunda
            - DB_PASSWORD=camunda
            - WAIT_FOR=mysql:3306
            - SPRING_MAIL_HOST=10.252.1.2
        links:
            - mysql
        volumes:
            - ./camunda/camunda-data/conf/camunda-data/conf:/camunda/conf
            - ./camunda/camunda-data/webapps/webapps:/camunda/webapps


    mysql:
       image: mysql:8.0
       mem_limit: 858m
       environment:
           - MYSQL_ROOT_PASSWORD=camunda
           - MYSQL_USER=camunda
           - MYSQL_PASSWORD=camunda
           - MYSQL_DATABASE=process-engine
       volumes:
           - ./camunda/mysql-data:/var/lib/mysql
       ports:
          - 3306:3306

